export const themes = {
  "💥": {
    white: "#FFDEF3",
    black: "black",
    bg: "#35212A",
    ground: "#35212A",
    mid: "#FF61BE",
    highlight: "#3B55CE",
    accent: "#FFDEF3",
  },
  "✨": {
    white: "#FFACFC",
    black: "black",
    bg: "#560A86",
    ground: "#560A86",
    mid: "#7122FA",
    highlight: "#F148FB",
    accent: "#7122FA",
  },
    "🌈": {
    white: "#d50000",
    black: "#AA00FF",
    bg: "#FFD600",
    ground: "#00C853",
    mid: "#2962FF",
    highlight: "#FF6D00",
    accent: "#03191E",
  },
  "🚿": {
    white: "#03191E",
    black: "#03191E",
    bg: "white",
    ground: "white",
    mid: "#51B9F6",
    highlight: "#0AEBD4",
    accent: "#03191E",
  },
  "📏": {
    white: "#2D2A32",
    black: "black",
    bg: "white",
    ground: "#6c696f",
    mid: "#EDEC93",
    highlight: "#EAE151",
    accent: "white",
  },
  "🍊": {
    white: "black",
    black: "black",
    bg: "#F5F5F6",
    ground: "#F5F5F6",
    mid: "#b0bec5",
    highlight: "#ff5722",
    accent: "#ff8a50",
  },
  "🥒": {
    white: "black",
    black: "black",
    bg: "#F5F5F6",
    ground: "#F5F5F6",
    mid: "#b0bec5",
    highlight: "#43a047",
    accent: "#76d275",
  },
  "🍅": {
    white: "black",
    black: "black",
    bg: "#F5F5F6",
    ground: "#F5F5F6",
    mid: "#b0bec5",
    highlight: "#f44336",
    accent: "#66bb6a",
  },
  "💙": {
    white: "black",
    black: "black",
    bg: "#F5F5F6",
    ground: "#F5F5F6",
    mid: "#b0bec5",
    highlight: "#2196f3",
    accent: "#6ec6ff",
  },
  "🍆": {
    white: "black",
    black: "black",
    bg: "#F5F5F6",
    ground: "#F5F5F6",
    mid: "#b0bec5",
    highlight: "#ba68c8",
    accent: "#ee98fb",
  },
  "🌊": {
    white: "black",
    black: "black",
    bg: "#dbdbd2",
    ground: "#dbdbd2",
    mid: "#e57373",
    highlight: "#2196f3",
    accent: "#FFC107",
  },
  "🤽‍♀️": {
    white: "white",
    black: "black",
    bg: "#591fce",
    ground: "#591fce",
    mid: "#0c9cee",
    highlight: "#a1f480",
    accent: "#3dbdc2",
  },
  "🌅": {
    white: "#f7ffba",
    black: "#733e18",
    bg: "#da8067",
    ground: "#da8067",
    mid: "#ebaf81",
    highlight: "#f7e39c",
    accent: "#f7e39c",
  },
  "⌨️": {
    white: "white",
    black: "black",
    bg: "black",
    ground: "black",
    mid: "yellowgreen",
    highlight: "yellowgreen",
    accent: "yellowgreen",
  },
  "🌞": {
    white: "black",
    black: "black",
    bg: "#ECEFF1",
    ground: "#ECEFF1",
    mid: "#78909C",
    highlight: "#8BC34A",
    accent: "#FFC107",
  },
  "🌑": {
    white: "white",
    black: "black",
    ground: "#33135C",
    bg: "#33135C",
    mid: "#652EC7",
    highlight: "#DE38C8",
    accent: "#FFD300",
  },
};